name = "ZeroInflatedDistributions"
uuid = "f0eaf0ea-6b2c-45fd-8e3c-3fe72bdc2ec5"
authors = ["John Best <jkbest@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"

[compat]
Distributions = "0.23"
StatsFuns = "0.9"
julia = "1.5"
